# Generated by Django 5.2.8 on 2025-11-20 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('contests', '0002_alter_contest_created_at_alter_contest_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='出题人'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='base_points',
            field=models.PositiveIntegerField(default=100, verbose_name='基础分值'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.challengecategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='contests.contest', verbose_name='所属比赛'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=256, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_case_insensitive',
            field=models.BooleanField(default=True, verbose_name='忽略大小写'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否开放'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='题目简介'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='题目标识'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='分类标识'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='solved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='解题时间'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_solves', to='contests.team', verbose_name='队伍'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_solves', to=settings.AUTH_USER_MODEL, verbose_name='选手'),
        ),
    ]
