# Generated by Django 5.2.8 on 2025-11-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_scoring_fields'),
        ('contests', '0004_contestscoreboard_alter_teammember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='dynamic_prefix',
            field=models.CharField(blank=True, default='FLAG', max_length=64, verbose_name='Flag 前缀'),
        ),
        migrations.AddIndex(
            model_name='challengehintunlock',
            index=models.Index(fields=['challenge', 'team'], name='challenges__challen_d99b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='challengehintunlock',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_30271c_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesolve',
            index=models.Index(fields=['challenge', 'solved_at'], name='challenges__challen_96e3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesolve',
            index=models.Index(fields=['challenge', 'team'], name='challenges__challen_507fae_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesolve',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_27cd70_idx'),
        ),
    ]
