# Generated by Django 5.2.8 on 2025-11-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengecategory_contest'),
        ('contests', '0007_alter_contest_is_team_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecategory',
            name='contest',
            field=models.ForeignKey(blank=True, help_text='分类归属的比赛，只能在该比赛内使用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_categories', to='contests.contest', verbose_name='所属比赛'),
        ),
    ]
