# Generated by Django 5.2.8 on 2025-12-02 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_challengecategory_contest'),
        ('contests', '0009_contestparticipant_is_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(help_text='创建题目的管理员/出题人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='出题人'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='base_points',
            field=models.PositiveIntegerField(default=100, help_text='初始分值，动态模式为起始分', verbose_name='基础分值'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='blood_bonus_points',
            field=models.JSONField(blank=True, default=list, help_text='按名次排列的额外加分列表', verbose_name='n血加分列表'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='blood_reward_count',
            field=models.PositiveIntegerField(default=0, help_text='享受 n 血奖励的解题名次数', verbose_name='n血数量'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='blood_reward_type',
            field=models.CharField(choices=[('none', '无奖励'), ('bonus', '加分奖励'), ('no_decay', '前 n 血不衰减')], default='none', help_text='n 血奖励策略，支持无/加分/前 n 血不衰减', max_length=16, verbose_name='n血奖励类型'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(help_text='题目分类，便于筛选，可留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.challengecategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(help_text='完整题面描述，包含背景与要求', verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='contest',
            field=models.ForeignKey(help_text='题目所属的比赛，用于限制可见范围', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='contests.contest', verbose_name='所属比赛'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='题目创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='decay_factor',
            field=models.FloatField(default=0.95, help_text='衰减参数，百分比或固定扣分值', verbose_name='衰减因子'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='decay_type',
            field=models.CharField(choices=[('percentage', '按百分比衰减'), ('fixed_step', '固定分值递减')], default='percentage', help_text='动态计分时的衰减方式', max_length=16, verbose_name='衰减类型'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='题目难度标签，供选手参考', max_length=20, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='dynamic_prefix',
            field=models.CharField(blank=True, default='FLAG', help_text='Flag 外层前缀，自动拼接 {flag}', max_length=64, verbose_name='Flag 前缀'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(help_text='静态题的 Flag 或动态题的种子', max_length=256, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_case_insensitive',
            field=models.BooleanField(default=True, help_text='判题时是否忽略大小写', verbose_name='忽略大小写'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_type',
            field=models.CharField(choices=[('static', '静态 Flag'), ('dynamic', '动态 Flag')], default='static', help_text='Flag 校验模式，静态或动态', max_length=16, verbose_name='Flag 类型'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, help_text='关闭后题目不会对选手开放', verbose_name='是否开放'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='min_score',
            field=models.PositiveIntegerField(default=50, help_text='动态计分可衰减到的最低得分', verbose_name='最低分'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scoring_mode',
            field=models.CharField(choices=[('fixed', '固定分值'), ('dynamic', '动态分值')], default='fixed', help_text='选择固定分值或动态衰减模式', max_length=16, verbose_name='计分模式'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(blank=True, help_text='列表视图展示的简短说明', max_length=255, verbose_name='题目简介'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(help_text='题目唯一标识，比赛内不可重复', max_length=200, verbose_name='题目标识'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(help_text='展示给选手的题目名称', max_length=200, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='题目最近更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='challengeattachment',
            name='challenge',
            field=models.ForeignKey(help_text='附件关联的题目', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengeattachment',
            name='name',
            field=models.CharField(help_text='附件显示名称', max_length=200, verbose_name='附件名称'),
        ),
        migrations.AlterField(
            model_name='challengeattachment',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='附件展示顺序', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='challengeattachment',
            name='url',
            field=models.URLField(help_text='附件的下载 URL', max_length=500, verbose_name='附件链接'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='description',
            field=models.TextField(blank=True, help_text='分类说明文字，可为空', verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='name',
            field=models.CharField(help_text='分类显示名称，后台与前台保持一致', max_length=80, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='challengecategory',
            name='slug',
            field=models.SlugField(help_text='分类唯一标识，供接口/URL 使用', max_length=80, verbose_name='分类标识'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='challenge',
            field=models.ForeignKey(help_text='提示所属的题目', on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='content',
            field=models.TextField(help_text='提示正文内容', verbose_name='提示内容'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='非免费提示的扣分成本', verbose_name='扣分成本'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='提示创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='is_free',
            field=models.BooleanField(default=True, help_text='标记提示是否免费可见', verbose_name='是否免费'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='提示展示顺序', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='title',
            field=models.CharField(help_text='提示显示标题', max_length=200, verbose_name='提示标题'),
        ),
        migrations.AlterField(
            model_name='challengehint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='提示最近更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='challenge',
            field=models.ForeignKey(help_text='提示所属题目，冗余便于查询', on_delete=django.db.models.deletion.CASCADE, related_name='hint_unlocks', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='本次解锁消耗的积分', verbose_name='扣分成本'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='hint',
            field=models.ForeignKey(help_text='被解锁的提示对象', on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='challenges.challengehint', verbose_name='提示'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='team',
            field=models.ForeignKey(blank=True, help_text='组队赛的所属队伍，个人赛留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hint_unlocks', to='contests.team', verbose_name='队伍'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='提示被解锁的时间', verbose_name='解锁时间'),
        ),
        migrations.AlterField(
            model_name='challengehintunlock',
            name='user',
            field=models.ForeignKey(help_text='发起解锁的用户', on_delete=django.db.models.deletion.CASCADE, related_name='hint_unlocks', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, help_text='本次解题获得的最终分值', verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, help_text='n 血奖励产生的额外加分', verbose_name='额外加分'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='challenge',
            field=models.ForeignKey(help_text='对应的题目记录', on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='solved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='解题完成的时间戳', verbose_name='解题时间'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='team',
            field=models.ForeignKey(blank=True, help_text='解题所属队伍，个人赛时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_solves', to='contests.team', verbose_name='队伍'),
        ),
        migrations.AlterField(
            model_name='challengesolve',
            name='user',
            field=models.ForeignKey(help_text='解出题目的用户', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_solves', to=settings.AUTH_USER_MODEL, verbose_name='选手'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='challenge',
            field=models.ForeignKey(help_text='子任务所属的题目', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='challenges.challenge', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='description',
            field=models.TextField(blank=True, help_text='子任务的具体说明，可为空', verbose_name='子任务描述'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='展示顺序，越小越靠前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='该子任务对应的参考分值', verbose_name='子任务分值'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='title',
            field=models.CharField(help_text='子任务名称，用于提示阶段目标', max_length=200, verbose_name='子任务标题'),
        ),
    ]
