# Generated by Django 5.2.8 on 2025-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banksolve',
            new_name='problem_ban_challen_d5970b_idx',
            old_name='problem_ba_challen_9ce2a9_idx',
        ),
    ]
