"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

"""
Config/settings.py
项目设置（Django + DRF）
- 默认值仅用于开发环境；生产环境请通过后台 System-系统配置 修改敏感配置后重启。
- 结构按功能分块，便于查阅：安全/应用/数据库/DRF/缓存/Docker/邮件/CORS/日志/Celery 等。
"""

# --------------------------------------------------------------------------------------
# 基础路径
# --------------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------------------
# 安全与调试
# --------------------------------------------------------------------------------------
# True 仅限用于开发环境；如需调试可在后台 SystemConfig 中修改并重启
SECRET_KEY = os.getenv("SECRET_KEY", 'django-insecure-DEFAULT-KEY-CHANGE-IN-PRODUCTION-VIA-ADMIN')
# 专用于 Flag 派生的高熵密钥，避免复用 SECRET_KEY；可在后台 SystemConfig 覆盖
FLAG_SECRET = os.getenv("FLAG_SECRET") or SECRET_KEY
# 默认开启 DEBUG 便于本地开发；生产需显式设置 DEBUG=false
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# 支持通过环境变量/后台配置收敛域名
_env_allowed_hosts = os.getenv("ALLOWED_HOSTS", "")
if _env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]

# CSRF 信任域名列表：首启为空，生产可通过环境变量或后台配置补充
_env_csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [h.strip() for h in _env_csrf_trusted.split(",") if h.strip()] if _env_csrf_trusted else []

# 登录验证码开关：默认关闭，需在环境变量/后台显式开启
ALLOW_LOGIN_WITHOUT_CAPTCHA = os.getenv("ALLOW_LOGIN_WITHOUT_CAPTCHA", "False").lower() == "true"

# 站点品牌名称（前台/后台可展示的品牌词），可在后台 SystemConfig 覆盖
SITE_BRAND = os.getenv("SITE_BRAND", "Find The Cat")

# JWT Cookie 模式开关：关闭后仅使用 Authorization 头，不再写入 JWT Cookie
JWT_USE_COOKIE = False
JWT_ACCESS_COOKIE_NAME = "jwt_token_in_cookie"

# WebSocket 连接与推送参数（后台可覆盖）：限流与榜单节流默认值
WS_MAX_CONNECTIONS_PER_USER = int(os.getenv("WS_MAX_CONNECTIONS_PER_USER", "5"))
WS_MAX_CONNECTIONS_PER_IP = int(os.getenv("WS_MAX_CONNECTIONS_PER_IP", "20"))
SCOREBOARD_PUSH_INTERVAL_SECONDS = int(os.getenv("SCOREBOARD_PUSH_INTERVAL_SECONDS", "3"))
SCOREBOARD_PUSH_TOP = int(os.getenv("SCOREBOARD_PUSH_TOP", "10"))
# 通知提前量（秒）
NOTIFY_CONTEST_START_SOON_SECONDS = int(os.getenv("NOTIFY_CONTEST_START_SOON_SECONDS", "3600"))
NOTIFY_CONTEST_FREEZE_SOON_SECONDS = int(os.getenv("NOTIFY_CONTEST_FREEZE_SOON_SECONDS", "900"))
NOTIFY_CONTEST_REG_DEADLINE_SOON_SECONDS = int(os.getenv("NOTIFY_CONTEST_REG_DEADLINE_SOON_SECONDS", "3600"))
NOTIFY_CONTEST_ENDING_SOON_SECONDS = int(os.getenv("NOTIFY_CONTEST_ENDING_SOON_SECONDS", "1800"))
NOTIFY_TEAM_MIN_MEMBERS = int(os.getenv("NOTIFY_TEAM_MIN_MEMBERS", "2"))

# --------------------------------------------------------------------------------------
# HTTPS / Cookie 安全（生产环境强制）
# --------------------------------------------------------------------------------------
# 透过代理传入 HTTPS 头时信任 X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# 非调试环境强制跳转到 HTTPS
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# --------------------------------------------------------------------------------------
# 应用模块（Django 内置 + 第三方 + 业务）
# --------------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django 内置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'channels',  # WebSocket/ASGI 支持
    'rest_framework',
    'corsheaders',  # pip install django-cors-headers
    'django_filters',
    'drf_spectacular',  # django rest framework 自动生成 API 文档
    'captcha',  # 图形验证码

    # 业务（完整路径 / 标签
    'apps.auth.apps.AuthConfig',  # 为避免与 django 内置权限类冲突，使用标准写法 '<module_path>.apps.<AppConfigClass>'
    'apps.accounts',
    'apps.contests',
    'apps.challenges',
    'apps.submissions',
    'apps.machines',
    'apps.problem_bank',
    'apps.system',
    'apps.notifications',
    # ...后续再扩充
]

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 自定义认证后端：后台登录时也能拿到 is_active=False 的用户对象，便于返回自定义失效提示
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.AdminAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --------------------------------------------------------------------------------------
# 中间件 (MIDDLEWARE)
# --------------------------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须放最前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "apps.common.middleware.RequestContextMiddleware",  # 放在认证后，确保能获取用户上下文
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------------------------------------
# URL / WSGI / TEMPLATES
# --------------------------------------------------------------------------------------
ROOT_URLCONF = 'Config.urls'
ASGI_APPLICATION = "Config.asgi.application"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'

# --------------------------------------------------------------------------------------
# 数据库（默认 sqlite，生产可切换 mysql/postgres）
# --------------------------------------------------------------------------------------
DB_ENGINE = os.getenv("DB_ENGINE", "postgres")
DB_NAME = os.getenv("DB_NAME", "ftc")
DB_USER = os.getenv("DB_USER", "ftc")
DB_PASSWORD = os.getenv("DB_PASSWORD", "ftc-pass")
DB_HOST = os.getenv("DB_HOST", "postgres")
DB_PORT = os.getenv("DB_PORT", "5432")

# 根据 DB_ENGINE 构建 DATABASES 配置
if DB_ENGINE.lower() in ('my', 'mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
elif DB_ENGINE.lower() in ('post', 'postgre', 'postgres', 'postgresql', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    # 默认 sqlite3（本地开发，无需额外配置）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / DB_NAME,
        }
    }

# --------------------------------------------------------------------------------------
# 密码校验
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        # 使用自定义校验器，保持与 API 密码规则一致（8-64 位且包含字母与数字）
        'NAME': 'apps.accounts.validators.AccountPasswordValidator',
    },
]

# --------------------------------------------------------------------------------------
# 国际化与时间
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# 项目级翻译目录，覆盖内置翻译
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# --------------------------------------------------------------------------------------
# 静态与媒体
# --------------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # 部署时 collectstatic 输出目录

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 用户上传（题目附件等）

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------------------
# DRF / 认证 / 过滤
# --------------------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.common.authentication.JWTAuthentication',  # apps/common/authentication.py
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'apps.common.permissions.IsAuthenticated',  # apps/common/permissions.py
    ),

    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardPagination',  # apps/common/pagination.py

    'EXCEPTION_HANDLER': 'apps.common.exception_handler.custom_exception_handler',  # apps/common/exception_handler.py

    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',   # 登录限流
        'register': '5/min',  # 注册限流
        'flag_submit': '10/min',    # Flag 提交限流
        'machine_start': '10/min',   # 靶机启动限流
        'user_post': '30/min',      # 普通用户写操作限流
        'attachment_upload': '10/min',  # 附件上传限流
        'email_code_send': '5/min', # 邮箱验证码发送限流
    },

    'DEFAULT_SCHEMA_CLASS': 'apps.common.openapi.ShortDescriptionAutoSchema',
}

# 默认仅启用 JSON 渲染，避免在前端暴露 DRF Browsable API/调试页面
REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = (
    'rest_framework.renderers.JSONRenderer',
)

SPECTACULAR_SETTINGS = {
    "TITLE": "FTC API",
    "VERSION": "1.0.0",
    # Bearer/JWT 认证声明
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    # 告诉 spectacular 我们的自定义认证类使用上述 Bearer 配置
    "AUTHENTICATION_WHITELIST": [
        "apps.common.authentication.JWTAuthentication",
    ],
    # 显式声明需要解析的认证类（便于加载 OpenAPI 扩展）
    "AUTHENTICATION_CLASSES": [
        "apps.common.authentication.JWTAuthentication",
    ],
    # 默认 schema 生成器：缺少描述时自动补充简短中文说明
    "DEFAULT_SCHEMA_CLASS": "apps.common.openapi.ShortDescriptionAutoSchema",
    # 自定义 operationId，按路径+方法自动生成唯一名称，避免冲突
    "OPERATION_ID_CALLBACK": "apps.common.openapi.build_operation_id",
    # 预定义标签顺序与描述，便于前端分组展示
    "TAGS": [
        {"name": "accounts-auth", "description": "角色与权限"},
        {"name": "accounts-password", "description": "密码修改与重置"},
        {"name": "accounts-email", "description": "账户邮箱管理"},
        {"name": "accounts-profile", "description": "个人资料管理"},
        {"name": "contests", "description": "比赛管理"},
        {"name": "challenges", "description": "题目管理与提示"},
        {"name": "submissions", "description": "提交判题与记录"},
        {"name": "machines", "description": "靶机管理"},
        {"name": "problem-bank", "description": "题库管理"},
        {"name": "teams", "description": "队伍管理"},
        {"name": "system", "description": "系统配置"},
        {"name": "health", "description": "健康检查"},
    ],
}

# --------------------------------------------------------------------------------------
# 缓存（Redis）
# --------------------------------------------------------------------------------------
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB_CACHE = int(os.getenv("REDIS_DB_CACHE", "0"))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 防止 Redis 未启用时阻塞：降低连接/读写超时并忽略异常（降级为无缓存）
            "SOCKET_CONNECT_TIMEOUT": float(os.getenv("REDIS_CONNECT_TIMEOUT", "0.2")),
            "SOCKET_TIMEOUT": float(os.getenv("REDIS_SOCKET_TIMEOUT", "0.5")),
            "IGNORE_EXCEPTIONS": True,
        },
    }
}

# Channels 通道层：优先使用 Redis，缺失依赖时回退内存层（单进程）
_channel_backend = "channels.layers.InMemoryChannelLayer"
_channel_config: dict = {}
if os.getenv("CHANNEL_LAYER_BACKEND", "redis").lower() == "redis":
    try:  # pragma: no cover - 依赖缺失时回退
        import channels_redis  # noqa: F401

        _channel_backend = "channels_redis.core.RedisChannelLayer"
        _channel_config = {
            "hosts": [
                (
                    os.getenv("CHANNEL_REDIS_HOST", REDIS_HOST),
                    int(os.getenv("CHANNEL_REDIS_PORT", REDIS_PORT)),
                )
            ]
        }
    except Exception:
        _channel_backend = "channels.layers.InMemoryChannelLayer"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": _channel_backend,
    }
}
if _channel_config:
    CHANNEL_LAYERS["default"]["CONFIG"] = _channel_config

# --------------------------------------------------------------------------------------
# Docker 配置（靶机容器）
# --------------------------------------------------------------------------------------
DOCKER_HOST = None  # Docker API endpoint，None 则用本地 socket/管道
DOCKER_TLS_VERIFY = False  # 远程 TLS 校验开关（远程 Docker 节点需启用）
DOCKER_CERT_PATH = None  # TLS 证书路径（包含 ca/cert/key）
DOCKER_USE_MOCK = False  # 是否启用 mock Docker（测试环境可设为 True）
DOCKER_NETWORK = None  # 可选 Docker 网络名称

# 靶机运行时默认值（题目模板可覆盖）
MACHINE_MAX_RUNTIME_MINUTES = 30  # 默认单个靶机实例最长运行时间（分钟）
MACHINE_CLEAN_INTERVAL_SECONDS = 300  # Celery 清理任务默认执行间隔（秒）
MACHINE_PORT_CACHE_TTL = 300  # 端口占用 Redis 缓存默认 TTL（秒）
# 靶机延时策略（管理员可在后台/环境变量中覆盖）
MACHINE_EXTEND_MINUTES_DEFAULT = int(os.getenv("MACHINE_EXTEND_MINUTES_DEFAULT", "30"))  # 单次延时分钟数
MACHINE_EXTEND_MAX_TIMES = os.getenv("MACHINE_EXTEND_MAX_TIMES", "-1")  # 每实例最大延时次数，-1 表示不限制
try:
    MACHINE_EXTEND_MAX_TIMES = int(MACHINE_EXTEND_MAX_TIMES)
except Exception:
    MACHINE_EXTEND_MAX_TIMES = -1
MACHINE_EXTEND_THRESHOLD_MINUTES = int(os.getenv("MACHINE_EXTEND_THRESHOLD_MINUTES", "15"))  # 剩余 <= 此阈值时可延时
MACHINE_EXPIRING_NOTIFY_MINUTES = int(os.getenv("MACHINE_EXPIRING_NOTIFY_MINUTES", "5"))  # 剩余时间提醒阈值

# --------------------------------------------------------------------------------------
# 邮件配置
# --------------------------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --------------------------------------------------------------------------------------
# CORS (跨域资源共享)
# --------------------------------------------------------------------------------------
# 默认收紧 CORS：仅允许本机/常用本地端口
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# 若通过后台 SystemConfig 配置了 CORS_ALLOWED_ORIGINS，则在 apps.system.services.apply_security_settings_from_config 中覆盖


# --------------------------------------------------------------------------------------
# 日志配置（自定义 logger，SystemConfig 可覆盖）
# --------------------------------------------------------------------------------------
# 禁用 Django 默认日志，使用自定义 logger（apps/common/infra/logger.py）
LOGGING_CONFIG = None

# 日志系统默认值（用于首次启动时初始化 SystemConfig），生产可在后台修改
LOG_PATH = "logs/"  # 日志目录；日志文件为 LOG_PATH/system.log

# 提前初始化日志系统（使用 settings 默认值，避免 AppConfig.ready 阶段访问数据库）
from apps.common.infra.logger import (  # noqa: E402
    configure_logging as _configure_ftc_logging,
    get_log_path_from_settings as _ftc_log_path_from_settings,
)

_configure_ftc_logging(
    force=True,
    log_file_path=_ftc_log_path_from_settings(),
)

# --------------------------------------------------------------------------------------
# Celery 配置
# --------------------------------------------------------------------------------------
# Celery Broker（任务队列）使用 Redis DB 1，可用环境变量覆盖
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/1")

# Celery Result Backend（任务结果存储）使用 Redis DB 2
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", f"redis://{REDIS_HOST}:{REDIS_PORT}/2")

# 默认队列名称
CELERY_TASK_DEFAULT_QUEUE = "default"

# Celery Beat 定时任务：靶机超时清理
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-machines": {
        "task": "apps.machines.tasks.cleanup_expired_machines",
        "schedule": timedelta(seconds=MACHINE_CLEAN_INTERVAL_SECONDS),
    },
    "notifications-scan-contests": {
        "task": "apps.notifications.tasks.scan_contests_for_notifications",
        "schedule": timedelta(seconds=300),
    },
}
