# Generated by Django 5.2.8 on 2025-11-20 14:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mailaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='头像链接，前端可使用对象存储上传后回填', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介 / 个性签名', verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='国家/地区，便于排行榜展示', max_length=64, verbose_name='国家/地区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='邮箱是否已通过验证码验证', verbose_name='邮箱已验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team_leader',
            field=models.BooleanField(default=False, help_text='是否担任当前队伍队长（Team 模块完善后会迁移为外键判断）', verbose_name='队长'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='昵称，默认等于用户名，可由选手自行修改', max_length=40, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='所属团队 / 学校 / 公司', max_length=120, verbose_name='所属单位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='所属队伍占位字段，后续 contests/teams 模块会替换为外键', null=True, verbose_name='队伍占位符'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='个人主页或其他社交链接', verbose_name='个人主页'),
        ),
    ]
