# Generated by Django 5.2.8 on 2025-11-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_systemconfig_detail_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key'], 'verbose_name': '基础配置', 'verbose_name_plural': '基础配置'},
        ),
    ]
