# Generated by Django 5.2.8 on 2025-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_alter_systemconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ 邮箱'), ('163', '163 邮箱'), ('gmail', 'Gmail'), ('outlook', 'Outlook 邮箱'), ('custom', '自定义 SMTP')], default='qq', max_length=20, verbose_name='服务商')),
                ('name', models.CharField(help_text='后台展示用名称', max_length=50, verbose_name='名称')),
                ('host', models.CharField(max_length=120, verbose_name='SMTP 主机')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='端口')),
                ('use_tls', models.BooleanField(default=True, verbose_name='启用 TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='启用 SSL')),
                ('username', models.EmailField(help_text='邮箱账号', max_length=254, verbose_name='用户名')),
                ('password', models.CharField(help_text='授权码或应用专用密码', max_length=255, verbose_name='密码')),
                ('from_name', models.CharField(blank=True, help_text='展示名', max_length=100, verbose_name='发信名称')),
                ('from_email', models.EmailField(blank=True, help_text='用于 From 的邮箱地址，默认等于 username', max_length=254, verbose_name='发信邮箱')),
                ('priority', models.PositiveIntegerField(default=100, help_text='数字越小优先级越高', verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, help_text='设为 True 后其余账号将自动取消默认', verbose_name='默认账号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发信账号',
                'verbose_name_plural': '发信账号',
                'ordering': ['priority', '-updated_at'],
            },
        ),
    ]
