# Generated by Django 5.2.8 on 2025-11-27 13:05
"""
数据迁移：将 MailAccount 从 accounts 模块迁移到 system 模块

迁移流程：
1. 新表已在 0008_mailaccount 创建（configs_mailaccount）
2. 本迁移将数据从旧表（accounts_mailaccount）复制到新表
3. accounts.0011_delete_mailaccount 将删除旧表

注意：
- 本迁移依赖 accounts 的 MailAccount 表存在
- 如果旧表不存在（全新数据库），则跳过复制
"""

from django.db import migrations


def copy_mailaccount_data(apps, schema_editor):
    """
    将 MailAccount 数据从 accounts_mailaccount 复制到 configs_mailaccount

    逻辑：
    - 使用原始 SQL 查询，避免依赖模型定义
    - 检查旧表是否存在，不存在则跳过（新数据库场景）
    - 逐条复制数据，保持所有字段值
    """
    from django.db import connection

    # 仅针对 SQLite 迁移旧数据，其他数据库（全新部署）直接跳过
    if connection.vendor != "sqlite":
        print("非 SQLite 数据库，跳过 MailAccount 数据迁移")
        return

    with connection.cursor() as cursor:
        # 检查旧表是否存在
        cursor.execute("""
            SELECT name FROM sqlite_master
            WHERE type='table' AND name='accounts_mailaccount'
        """)
        if not cursor.fetchone():
            # 旧表不存在，跳过数据复制（全新数据库）
            print("旧表 accounts_mailaccount 不存在，跳过数据迁移")
            return

        # 复制数据：从 accounts_mailaccount 到 configs_mailaccount
        cursor.execute("""
            INSERT INTO configs_mailaccount (
                id, provider, name, host, port, use_tls, use_ssl,
                username, password, from_name, from_email,
                priority, is_active, is_default, created_at, updated_at
            )
            SELECT
                id, provider, name, host, port, use_tls, use_ssl,
                username, password, from_name, from_email,
                priority, is_active, is_default, created_at, updated_at
            FROM accounts_mailaccount
        """)

        # 获取复制的记录数
        copied_count = cursor.rowcount
        print(f"已将 {copied_count} 条 MailAccount 记录从 accounts 迁移到 system")


def reverse_copy_mailaccount_data(apps, schema_editor):
    """
    回滚操作：将数据从 configs_mailaccount 复制回 accounts_mailaccount

    注意：
    - 回滚时 accounts_mailaccount 表应该已被重建
    - 本函数假设表结构相同
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # 清空旧表（如果存在）
        cursor.execute("DELETE FROM accounts_mailaccount")

        # 将数据复制回去
        cursor.execute("""
            INSERT INTO accounts_mailaccount (
                id, provider, name, host, port, use_tls, use_ssl,
                username, password, from_name, from_email,
                priority, is_active, is_default, created_at, updated_at
            )
            SELECT
                id, provider, name, host, port, use_tls, use_ssl,
                username, password, from_name, from_email,
                priority, is_active, is_default, created_at, updated_at
            FROM configs_mailaccount
        """)

        print("已将 MailAccount 数据回滚至 accounts 模块")


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0008_mailaccount'),
        ('accounts', '0010_alter_mailaccount_host'),  # 确保旧表存在
    ]

    operations = [
        migrations.RunPython(
            copy_mailaccount_data,
            reverse_code=reverse_copy_mailaccount_data
        ),
    ]
