# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0010_emailverificationcode_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='日志类型')),
                ('description', models.TextField(verbose_name='说明')),
            ],
            options={
                'verbose_name': 'SYSTEM',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log_category_view',
                'managed': False,
            },
        ),
    ]
