# Generated by Django 5.2.8 on 2025-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0012_remove_docker_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='verification_subject',
            field=models.CharField(blank=True, default='您的验证码', help_text='用于邮箱验证码的邮件主题，留空则使用默认“您的验证码”', max_length=120, verbose_name='验证码邮件主题'),
        ),
    ]
