# Generated by Django 5.2.8 on 2025-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0013_mailaccount_verification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='from_email',
            field=models.EmailField(blank=True, help_text='用于 From 的邮箱地址，固定等于用户名', max_length=254, verbose_name='发信邮箱'),
        ),
    ]
