# Generated by Django 5.2.8 on 2025-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0014_alter_mailaccount_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='logo',
            field=models.ImageField(blank=True, help_text='可选，上传后作为验证码邮件 Logo 展示', null=True, upload_to='mail_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='可选，填写后邮件页脚展示站点链接', verbose_name='网站链接'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='support_email',
            field=models.EmailField(blank=True, default='', help_text='留空则默认等于用户名，用于邮件页脚的联系邮箱', max_length=254, verbose_name='支持邮箱'),
        ),
    ]
