# Generated by Django 5.2.8 on 2025-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0015_mailaccount_logo_mailaccount_site_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='verification_subject',
            field=models.CharField(blank=True, default='', help_text='用于邮箱验证码的邮件主题，留空则使用默认“您的验证码”', max_length=120, verbose_name='验证码邮件主题'),
        ),
    ]
