# Generated by Django 5.2.8 on 2025-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0016_alter_mailaccount_verification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='verification_expire_minutes',
            field=models.PositiveIntegerField(default=10, help_text='单位分钟，留空使用默认 10 分钟，必须为正整数', verbose_name='验证码有效时间（分钟）'),
        ),
    ]
