# Generated by Django 5.2.8 on 2025-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0018_emailverificationcode_change_password_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='verification_expire_minutes',
            field=models.PositiveIntegerField(default=10, help_text='单位分钟，使用默认 10 分钟，必须为正整数', verbose_name='验证码有效时间（分钟）'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='verification_subject',
            field=models.CharField(blank=True, default='', help_text='用于邮箱验证码的邮件主题，留空则使用默认“您的验证码”', max_length=120, verbose_name='邮件主题'),
        ),
    ]
