# Generated by Django 5.2.8 on 2025-12-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_47e85c_idx',
            old_name='notifications_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_fbaa50_idx',
            old_name='notifications_user_type_created_idx',
        ),
    ]
