# Generated by Django 5.2.8 on 2025-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifications_user_read_idx_notificatio_user_id_47e85c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contest_new', '新比赛发布'), ('contest_registration_open', '报名开启'), ('contest_registration_deadline_soon', '报名截止前预警'), ('contest_registration_invalidated', '报名失效'), ('contest_upcoming', '即将开赛'), ('contest_started', '比赛开始'), ('contest_freeze_soon', '封榜前提醒'), ('contest_freeze', '封榜生效'), ('contest_ending_soon', '结束前提醒'), ('contest_ended', '比赛结束'), ('contest_announcement_new', '新公告'), ('challenge_new', '新题上线'), ('challenge_updated', '题目更新'), ('hint_unlocked', '提示已解锁'), ('team_member_joined', '队员加入'), ('team_member_left', '队员退出'), ('team_captain_transferred', '队长移交'), ('team_disbanded', '队伍解散'), ('team_invite_reset', '邀请码重置'), ('team_roster_warning', '队伍人数预警'), ('machine_started', '靶机启动'), ('machine_expiring', '靶机即将到期'), ('machine_expired', '靶机已回收'), ('machine_heartbeat_miss', '靶机心跳异常')], max_length=64, verbose_name='通知类型'),
        ),
    ]
