# Generated by Django 5.2.8 on 2025-11-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_dynamic_prefix_and_more'),
        ('contests', '0004_contestscoreboard_alter_teammember_options_and_more'),
        ('machines', '0002_remove_machineinstance_dynamic_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machineinstance',
            index=models.Index(fields=['contest', 'challenge', 'user', 'status'], name='machines_ma_contest_3b3e08_idx'),
        ),
        migrations.AddIndex(
            model_name='machineinstance',
            index=models.Index(fields=['port'], name='machines_ma_port_f1dbdd_idx'),
        ),
    ]
