# Generated by Django 5.2.8 on 2025-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_challengemachineconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengemachineconfig',
            name='compose_template',
        ),
    ]
