# Generated by Django 5.2.8 on 2025-11-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestannouncement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestScoreboard',
            fields=[
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contests.contest',),
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': '参赛队伍成员', 'verbose_name_plural': '参赛队伍成员'},
        ),
        migrations.AddIndex(
            model_name='contestannouncement',
            index=models.Index(fields=['contest', 'is_active', 'created_at'], name='contests_co_contest_4babc6_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'is_active'], name='contests_te_team_id_4bb5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'user', 'is_active'], name='contests_te_team_id_e703b9_idx'),
        ),
    ]
