# Generated by Django 5.2.8 on 2025-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contestscoreboard_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': '队伍', 'verbose_name_plural': '队伍'},
        ),
    ]
