# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_alter_contestannouncement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='is_team_based',
            field=models.BooleanField(default=True, verbose_name='团队赛'),
        ),
    ]
