# Generated by Django 5.2.8 on 2025-12-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_alter_contest_is_team_based'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('running', '进行中'), ('finished', '已结束')], default='registered', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest', verbose_name='比赛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '比赛参与记录',
                'verbose_name_plural': '比赛参与记录',
                'indexes': [models.Index(fields=['contest', 'status'], name='contests_co_contest_c377f1_idx'), models.Index(fields=['user', 'status'], name='contests_co_user_id_6dcd8d_idx')],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
