# Generated by Django 5.2.8 on 2025-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_contestparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='报名有效'),
        ),
    ]
