# Generated by Django 5.2.8 on 2025-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contestannouncement_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestannouncement',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='公告摘要'),
        ),
    ]
