# Generated by Django 5.2.8 on 2025-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_contest_registration_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='registration_start_time',
            field=models.DateTimeField(blank=True, help_text='设置后不可再调整，如需变更请联系管理员重置比赛', null=True, verbose_name='报名开始时间'),
        ),
    ]
