# Generated by Django 5.2.8 on 2025-11-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_alter_systemconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key'], 'verbose_name': 'SYSTEM', 'verbose_name_plural': '基础配置'},
        ),
    ]
