"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# --------------------------------------------------------------------------------------
# 基本路径
# --------------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# --------------------------------------------------------------------------------------
# 安全与调试
# --------------------------------------------------------------------------------------
# 注意：以下配置为默认值（开发环境），首次启动后会自动填入后台"基础配置"
# 生产环境请在后台修改为安全值后重启服务

# Django 核心安全密钥（必须在生产环境通过后台修改为强随机值）
SECRET_KEY = 'django-insecure-DEFAULT-KEY-CHANGE-IN-PRODUCTION-VIA-ADMIN'

# 调试模式（生产环境通过后台设为 False）
DEBUG = True

# 允许访问的主机列表（生产环境通过后台配置实际域名/IP）
ALLOWED_HOSTS = ["*"]

# 是否允许登录跳过图形验证码（生产环境应通过后台设为 False）
ALLOW_LOGIN_WITHOUT_CAPTCHA = True


# --------------------------------------------------------------------------------------
# 应用
# --------------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django 内置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'rest_framework',
    'corsheaders',  # pip install django-cors-headers
    'django_filters',
    'drf_spectacular',  # django rest framework 自动生成 API 文档
    'captcha',  # 图形验证码

    # 业务
    'apps.accounts',
    'apps.contests',
    'apps.challenges',
    'apps.submissions',
    'apps.machines',
    'apps.problem_bank',
    'apps.system',
    # ...后续再扩充
]

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 自定义认证后端：后台登录时也能拿到 is_active=False 的用户对象，便于返回自定义失效提示
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.AdminAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --------------------------------------------------------------------------------------
# 中间件
# --------------------------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须放最前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "apps.common.middleware.RequestContextMiddleware",  # 放在认证后，确保能获取用户上下文
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------------------------------------
# URL / WSGI / TEMPLATES
# --------------------------------------------------------------------------------------
ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'
# 如使用 Channels，可再配置 ASGI


# --------------------------------------------------------------------------------------
# 数据库
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 注意：
# - Django 启动时必须连接数据库，因此数据库配置必须在 settings.py 中提供
# - 默认使用 sqlite3（开发环境），生产环境可通过后台"基础配置"切换为 MySQL/PostgreSQL
# - 切换数据库引擎后需要：① 在后台填写连接参数 ② 重启 Django 服务

# 数据库引擎默认值（开发环境使用 sqlite，生产环境通过后台改为 mysql/postgres）
DB_ENGINE = 'sqlite'
DB_NAME = 'db.sqlite3'
DB_USER = ''
DB_PASSWORD = ''
DB_HOST = ''
DB_PORT = ''

# 根据 DB_ENGINE 构建 DATABASES 配置
if DB_ENGINE.lower() in ('my', 'mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
elif DB_ENGINE.lower() in ('post', 'postgre', 'postgres', 'postgresql', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    # 默认 sqlite3（本地开发，无需额外配置）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / DB_NAME,
        }
    }

# --------------------------------------------------------------------------------------
# 密码校验
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------------------------
# 国际化与时间
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# 项目级翻译目录，覆盖内置翻译
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# --------------------------------------------------------------------------------------
# 静态与媒体
# --------------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # 部署时 collectstatic 输出目录

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 用户上传（题目附件等）

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------------------
# DRF / 认证 / 过滤
# --------------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # 默认使用 JWT 来进行认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.common.authentication.JWTAuthentication',  # apps/common/authentication.py
        # 如需同时支持会话登录，可追加：
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    # 所有 API 默认都必须登录才能访问
    'DEFAULT_PERMISSION_CLASSES': (
        'apps.common.permissions.IsAuthenticated',  # apps/common/permissions.py
    ),

    # 让 DRF 支持通过 URL 参数构造过滤条件
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20,

    # 自定义分页器
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardPagination',  # apps/common/pagination.py

    # 自定义异常处理器
    'EXCEPTION_HANDLER': 'apps.common.exception_handler.custom_exception_handler',  # apps/common/exception_handler.py

    # 统一限速配置
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'flag_submit': '10/min',
        'machine_start': '3/min',
        'user_post': '30/min',
        'attachment_upload': '10/min',
    },

    # 自动生成 API 文档：
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FTC API",
    "VERSION": "1.0.0",
    # Bearer/JWT 认证声明
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    # 告诉 spectacular 我们的自定义认证类使用上述 Bearer 配置
    "AUTHENTICATION_WHITELIST": [
        "apps.common.authentication.JWTAuthentication",
    ],
    # 显式声明需要解析的认证类（便于加载 OpenAPI 扩展）
    "AUTHENTICATION_CLASSES": [
        "apps.common.authentication.JWTAuthentication",
    ],
}

# 按需调整 token 过期时间
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }


# --------------------------------------------------------------------------------------
# 缓存（Redis）
# --------------------------------------------------------------------------------------
# 注意：
# - Redis 配置的默认值适用于本地开发环境（127.0.0.1:6379）
# - 生产环境可通过后台"基础配置"修改为实际 Redis 服务器地址
# - Redis 用于：缓存、限流、记分板、Celery 队列，修改后需重启服务生效

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB_CACHE = 0

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# --------------------------------------------------------------------------------------
# Docker 配置（用于靶机容器）
# --------------------------------------------------------------------------------------
# 注意：
# - Docker 配置默认值适用于本地开发环境（使用本地 Docker Desktop/Daemon）
# - 生产环境可通过后台"基础配置"配置远程 Docker 节点、TLS 证书、镜像仓库等
# - 修改后需重启服务生效

DOCKER_HOST = None  # Docker API endpoint，None 则用本地 socket/管道
DOCKER_TLS_VERIFY = False  # 远程 TLS 校验开关（远程 Docker 节点需启用）
DOCKER_CERT_PATH = None  # TLS 证书路径（包含 ca/cert/key）
DOCKER_USE_MOCK = False  # 是否启用 mock Docker（测试环境可设为 True）
DOCKER_NETWORK = None  # 可选 Docker 网络名称

# 靶机运行时默认值（题目模板可覆盖）
MACHINE_MAX_RUNTIME_MINUTES = 30  # 默认单个靶机实例最长运行时间（分钟）
MACHINE_CLEAN_INTERVAL_SECONDS = 300  # Celery 清理任务默认执行间隔（秒）
MACHINE_PORT_CACHE_TTL = 300  # 端口占用 Redis 缓存默认 TTL（秒）

# --------------------------------------------------------------------------------------
# 邮件配置
# --------------------------------------------------------------------------------------
# 注意：
# 开发环境使用 console 后端（邮件输出到控制台，不实际发送）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 生产环境应通过 system 模块的 MailAccount 配置 SMTP
# MailAccount 会动态选择默认账号或指定账号发送邮件

# --------------------------------------------------------------------------------------
# CORS (跨域资源共享) 设置
# --------------------------------------------------------------------------------------
# 开发环境
CORS_ALLOW_ALL_ORIGINS = True

# 生产环境
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]


# --------------------------------------------------------------------------------------
# Spectacular OpenAPI 扩展加载（注册自定义 JWT 认证扩展）
# --------------------------------------------------------------------------------------
from apps.common import openapi as _common_openapi  # noqa: F401

# --------------------------------------------------------------------------------------
# 日志配置
# --------------------------------------------------------------------------------------
# 注意：
# - 日志配置的默认值适用于本地开发环境
# - 生产环境可通过后台"基础配置"调整日志级别、格式、文件路径
# - 修改后需重启服务生效

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_FILE = str(LOG_DIR / "ftc.log")  # 日志文件路径（默认 logs/ftc.log）
# --------------------------------------------------------------------------------------
# 日志配置
# --------------------------------------------------------------------------------------
# 注意：
# - 日志配置现在从系统配置（SystemConfig）中读取LOG_OUTPUT_LEVEL和LOG_PATH
# - 禁用Django默认的LOGGING配置，使用FTC自定义日志系统（apps/common/infra/logger.py）
# - 日志系统在应用启动时通过SystemConfig.apps.ready()初始化
# - 符合标准：docs/日志标准.md

# 禁用Django默认的日志配置
LOGGING_CONFIG = None

# 日志系统默认值（用于首次启动时初始化SystemConfig）
LOG_OUTPUT_LEVEL = "Medium"  # 日志输出级别：Low/Medium/High
LOG_PATH = "logs/"  # 日志文件路径

# 以下配置已废弃，保留用于参考
# LOG_LEVEL = "INFO"  # 已迁移至 SystemConfig.LOG_OUTPUT_LEVEL
# LOG_FORMAT = "json"  # 日志格式由日志标准统一规定（PLAIN格式）
# LOG_FILE = ...  # 已迁移至 SystemConfig.LOG_PATH

# 提前初始化日志系统（使用 settings 默认值，避免 AppConfig.ready 阶段访问数据库）
from apps.common.infra.logger import (  # noqa: E402
    configure_logging as _configure_ftc_logging,
    get_log_level_from_settings as _ftc_log_level_from_settings,
    get_log_path_from_settings as _ftc_log_path_from_settings,
)

_configure_ftc_logging(
    force=True,
    level=_ftc_log_level_from_settings(),
    log_file_path=_ftc_log_path_from_settings(),
)

# --------------------------------------------------------------------------------------
# Celery 配置
# --------------------------------------------------------------------------------------
# 注意：
# - Celery 用于异步任务（如定时清理超时靶机）
# - Broker 和 Result Backend 默认使用 Redis 的不同库（避免键冲突）
# - 生产环境可通过后台"基础配置"调整 Redis 库索引、队列名称等
# - 修改后需重启 Celery Worker 和 Beat 生效

# Celery Broker（任务队列）使用 Redis DB 1
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"

# Celery Result Backend（任务结果存储）使用 Redis DB 2
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"

# 默认队列名称
CELERY_TASK_DEFAULT_QUEUE = "default"

# Celery Beat 定时任务：靶机超时清理
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-machines": {
        "task": "apps.machines.tasks.cleanup_expired_machines",
        "schedule": timedelta(seconds=MACHINE_CLEAN_INTERVAL_SECONDS),
    }
}
