"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# --------------------------------------------------------------------------------------
# 基本路径
# --------------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# --------------------------------------------------------------------------------------
# 安全与调试
# --------------------------------------------------------------------------------------
# 开发环境
SECRET_KEY = 'django-insecure-a!(0n*euw%0(fy%sq*v#n8j2+0klghi^4oxsavef1u8$fcs@!l'
DEBUG = True
ALLOWED_HOSTS = ["*"]  # 允许访问的域名/IP

# 是否允许登录不带图形验证码（生产建议 False；测试/DEBUG 可设 True）
ALLOW_LOGIN_WITHOUT_CAPTCHA: bool = DEBUG

# 生产环境（部署时启用）
# SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-a!(0n*euw%0(fy%sq*v#n8j2+0klghi^4oxsavef1u8$fcs@!l")
# DEBUG = os.getenv("DEBUG", "False") == "True"
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# --------------------------------------------------------------------------------------
# 应用
# --------------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django 内置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'rest_framework',
    'corsheaders',  # pip install django-cors-headers
    'django_filters',
    'drf_spectacular',  # django rest framework 自动生成 API 文档
    'captcha',  # 图形验证码

    # 业务
    'apps.accounts',
    'apps.contests',
    'apps.challenges',
    'apps.submissions',
    'apps.machines',
    'apps.problem_bank',
    'apps.system',
    # ...后续再扩充
]

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 自定义认证后端：后台登录时也能拿到 is_active=False 的用户对象，便于返回自定义失效提示
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.AdminAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --------------------------------------------------------------------------------------
# 中间件
# --------------------------------------------------------------------------------------
MIDDLEWARE = [
    "apps.common.middleware.RequestContextMiddleware",
    'corsheaders.middleware.CorsMiddleware',  # 必须放最前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------------------------------------
# URL / WSGI / TEMPLATES
# --------------------------------------------------------------------------------------
ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'
# 如使用 Channels，可再配置 ASGI


# --------------------------------------------------------------------------------------
# 数据库（默认 sqlite；可通过环境变量切换到 MySQL / Postgres）
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE in ('my', 'mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'mysql'),
            'USER': os.getenv('DB_USER', 'defaultUser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'mysql'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
elif DB_ENGINE in ('post', 'postgre', 'postgres', 'postgresql', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'defaultUser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgresql'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# --------------------------------------------------------------------------------------
# 密码校验
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------------------------
# 国际化与时间
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# 项目级翻译目录，覆盖内置翻译
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# --------------------------------------------------------------------------------------
# 静态与媒体
# --------------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # 部署时 collectstatic 输出目录

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 用户上传（题目附件等）

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------------------
# DRF / 认证 / 过滤
# --------------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # 默认使用 JWT 来进行认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.common.authentication.JWTAuthentication',  # apps/common/authentication.py
        # 如需同时支持会话登录，可追加：
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    # 所有 API 默认都必须登录才能访问
    'DEFAULT_PERMISSION_CLASSES': (
        'apps.common.permissions.IsAuthenticated',  # apps/common/permissions.py
    ),

    # 让 DRF 支持通过 URL 参数构造过滤条件
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20,

    # 自定义分页器
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardPagination',  # apps/common/pagination.py

    # 自定义异常处理器
    'EXCEPTION_HANDLER': 'apps.common.exception_handler.custom_exception_handler',  # apps/common/exception_handler.py

    # 统一限速配置
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'flag_submit': '10/min',
        'machine_start': '3/min',
        'user_post': '30/min',
        'attachment_upload': '10/min',
    },

    # 自动生成 API 文档：
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FTC API",
    "VERSION": "1.0.0",
    # Bearer/JWT 认证声明
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    # 告诉 spectacular 我们的自定义认证类使用上述 Bearer 配置
    "AUTHENTICATION_WHITELIST": [
        "apps.common.authentication.JWTAuthentication",
    ],
    # 显式声明需要解析的认证类（便于加载 OpenAPI 扩展）
    "AUTHENTICATION_CLASSES": [
        "apps.common.authentication.JWTAuthentication",
    ],
}

# 按需调整 token 过期时间
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }


# --------------------------------------------------------------------------------------
# 缓存（Redis）
# --------------------------------------------------------------------------------------
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB_CACHE = int(os.getenv("REDIS_DB_CACHE", "0"))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# --------------------------------------------------------------------------------------
# Docker 配置（用于靶机容器）
# --------------------------------------------------------------------------------------
DOCKER_HOST = os.getenv("DOCKER_HOST", None)  # Docker API endpoint，None 则用本地 socket/管道
DOCKER_TLS_VERIFY = os.getenv("DOCKER_TLS_VERIFY", "0")  # 远程 TLS 校验开关
DOCKER_CERT_PATH = os.getenv("DOCKER_CERT_PATH", None)  # TLS 证书路径（包含 ca/cert/key）
DOCKER_USE_MOCK = os.getenv("DOCKER_USE_MOCK", "0") == "1"  # 是否启用 mock Docker
DOCKER_IMAGE_PREFIX = os.getenv("DOCKER_IMAGE_PREFIX", "")  # 镜像前缀（如私有仓库）
DOCKER_IMAGE_TAG = os.getenv("DOCKER_IMAGE_TAG", "latest")  # 镜像标签
DOCKER_CONTAINER_PORT = int(os.getenv("DOCKER_CONTAINER_PORT", "80"))  # 容器内服务端口
DOCKER_NETWORK = os.getenv("DOCKER_NETWORK", None)  # 可选 Docker 网络

# 靶机运行时长（分钟）与清理间隔（秒）
MACHINE_MAX_RUNTIME_MINUTES = int(os.getenv("MACHINE_MAX_RUNTIME_MINUTES", "30"))  # 单实例最长运行时间
MACHINE_CLEAN_INTERVAL_SECONDS = int(os.getenv("MACHINE_CLEAN_INTERVAL_SECONDS", "300"))  # 超时清理任务间隔
MACHINE_PORT_CACHE_TTL = int(os.getenv("MACHINE_PORT_CACHE_TTL", "300"))  # 端口占用缓存 TTL
SCOREBOARD_CACHE_TTL = int(os.getenv("SCOREBOARD_CACHE_TTL", "30"))  # 记分板缓存秒数

# --------------------------------------------------------------------------------------
# 邮件配置
# --------------------------------------------------------------------------------------

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')

EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', '').lower()

PROVIDER_DEFAULTS = {
    'qq': {'host': 'smtp.qq.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
    '163': {'host': 'smtp.163.com', 'port': 465, 'use_tls': False, 'use_ssl': True},
    'gmail': {'host': 'smtp.gmail.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
    'outlook': {'host': 'smtp.office365.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
}

provider_config = PROVIDER_DEFAULTS.get(EMAIL_PROVIDER, {})

EMAIL_HOST = os.getenv('EMAIL_HOST', provider_config.get('host', ''))
EMAIL_PORT = int(os.getenv('EMAIL_PORT') or provider_config.get('port', 587))
EMAIL_USE_TLS = (os.getenv('EMAIL_USE_TLS') or str(provider_config.get('use_tls', True))) == 'True'
EMAIL_USE_SSL = (os.getenv('EMAIL_USE_SSL') or str(provider_config.get('use_ssl', False))) == 'True'

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@ftc.local')


# --------------------------------------------------------------------------------------
# 邮件配置强校验
# --------------------------------------------------------------------------------------

def _require_setting(name: str, value: str) -> None:
    if not value:
        raise ImproperlyConfigured(f"邮件配置错误：{name} 不能为空，请检查环境变量 .env")


# 只在使用 SMTP 后端 且 非 DEBUG 环境时强校验
if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend' and not DEBUG:
    # 1. 必须有合法的 provider（或自定义 EMAIL_HOST）
    if not EMAIL_PROVIDER and not EMAIL_HOST:
        raise ImproperlyConfigured(
            "邮件配置错误：必须设置 EMAIL_PROVIDER 或 EMAIL_HOST 其一"
        )
    if EMAIL_PROVIDER and EMAIL_PROVIDER not in PROVIDER_DEFAULTS:
        raise ImproperlyConfigured(
            f"邮件配置错误：不支持的 EMAIL_PROVIDER={EMAIL_PROVIDER}，"
            f"可选值为：{', '.join(PROVIDER_DEFAULTS.keys())}"
        )

    # 2. 必须设置发信账号、授权码和默认发件人
    _require_setting("EMAIL_HOST_USER", EMAIL_HOST_USER)
    _require_setting("EMAIL_HOST_PASSWORD", EMAIL_HOST_PASSWORD)
    _require_setting("DEFAULT_FROM_EMAIL", DEFAULT_FROM_EMAIL)

# --------------------------------------------------------------------------------------
# CORS (跨域资源共享) 设置
# --------------------------------------------------------------------------------------
# 开发环境
CORS_ALLOW_ALL_ORIGINS = True

# 生产环境
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]


# --------------------------------------------------------------------------------------
# Spectacular OpenAPI 扩展加载（注册自定义 JWT 认证扩展）
# --------------------------------------------------------------------------------------
from apps.common import openapi as _common_openapi  # noqa: F401

# --------------------------------------------------------------------------------------
# 日志配置：默认输出到本地日志文件（不落 stdout）
# --------------------------------------------------------------------------------------
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_FILE = os.getenv("LOG_FILE", str(LOG_DIR / "ftc.log"))
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_FORMAT = os.getenv("LOG_FORMAT", "json").lower()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s [request_id=%(request_id)s user_id=%(user_id)s ip=%(ip)s path=%(path)s method=%(method)s]",
        },
        "json": {
            "format": '{"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s","request_id":"%(request_id)s","user_id":"%(user_id)s","ip":"%(ip)s","path":"%(path)s","method":"%(method)s"}',
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_FILE,
            "formatter": "json" if LOG_FORMAT == "json" else "plain",
            "encoding": "utf-8",
            "filters": ["request_context"],
        },
    },
    "filters": {
        "request_context": {
            "()": "apps.common.infra.logger.RequestContextFilter",
        }
    },
    "root": {
        "handlers": ["file"],
        "level": LOG_LEVEL,
    },
}

# --------------------------------------------------------------------------------------
# Celery 配置
# --------------------------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    f"redis://{REDIS_HOST}:{REDIS_PORT}/{os.getenv('REDIS_DB_CELERY', '1')}",
)
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    f"redis://{REDIS_HOST}:{REDIS_PORT}/{os.getenv('REDIS_DB_CELERY_RESULT', '2')}",
)
# 默认队列名称
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "default")
# Celery Beat 定时任务：靶机超时清理
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-machines": {
        "task": "apps.machines.tasks.cleanup_expired_machines",
        "schedule": timedelta(seconds=MACHINE_CLEAN_INTERVAL_SECONDS),
    }
}
