"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# --------------------------------------------------------------------------------------
# 基本路径
# --------------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# --------------------------------------------------------------------------------------
# 安全与调试
# --------------------------------------------------------------------------------------
# 开发环境
SECRET_KEY = 'django-insecure-a!(0n*euw%0(fy%sq*v#n8j2+0klghi^4oxsavef1u8$fcs@!l'
DEBUG = True
ALLOWED_HOSTS = ["*"]  # 允许访问的域名/IP

# 生产环境（部署时启用）
# SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-a!(0n*euw%0(fy%sq*v#n8j2+0klghi^4oxsavef1u8$fcs@!l")
# DEBUG = os.getenv("DEBUG", "False") == "True"
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# --------------------------------------------------------------------------------------
# 应用
# --------------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django 内置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'rest_framework',
    'corsheaders',  # pip install django-cors-headers
    'django_filters',
    'drf_spectacular',  # django rest framework 自动生成 API 文档

    # 业务
    'apps.accounts',
    'apps.contests',
    'apps.challenges',
    'apps.submissions',
    'apps.machines',
    # ...后续再扩充
]

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

# 自定义认证后端：后台登录时也能拿到 is_active=False 的用户对象，便于返回自定义失效提示
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.AdminAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --------------------------------------------------------------------------------------
# 中间件
# --------------------------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须放最前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------------------------------------------
# URL / WSGI / TEMPLATES
# --------------------------------------------------------------------------------------
ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'
# 如使用 Channels，可再配置 ASGI


# --------------------------------------------------------------------------------------
# 数据库（默认 sqlite；可通过环境变量切换到 MySQL / Postgres）
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE in ('my', 'mysql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'mysql'),
            'USER': os.getenv('DB_USER', 'defaultUser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'mysql'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
elif DB_ENGINE in ('post', 'postgre', 'postgres', 'postgresql', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'defaultUser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgresql'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# --------------------------------------------------------------------------------------
# 密码校验
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------------------------
# 国际化与时间
# --------------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# 项目级翻译目录，覆盖内置翻译
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# --------------------------------------------------------------------------------------
# 静态与媒体
# --------------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # 部署时 collectstatic 输出目录

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 用户上传（题目附件等）

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------------------
# DRF / 认证 / 过滤
# --------------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # 默认使用 JWT 来进行认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.common.authentication.JWTAuthentication',  # apps/common/authentication.py
        # 如需同时支持会话登录，可追加：
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    # 所有 API 默认都必须登录才能访问
    'DEFAULT_PERMISSION_CLASSES': (
        'apps.common.permissions.IsAuthenticated',  # apps/common/permissions.py
    ),

    # 让 DRF 支持通过 URL 参数构造过滤条件
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20,

    # 自定义分页器
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardPagination',  # apps/common/pagination.py

    # 自定义异常处理器
    'EXCEPTION_HANDLER': 'apps.common.exception_handler.custom_exception_handler',  # apps/common/exception_handler.py

    # 统一限速配置
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'flag_submit': '10/min',
        'machine_start': '3/min',
        'user_post': '30/min',
    },

    # 自动生成 API 文档：
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# 按需调整 token 过期时间
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }


# --------------------------------------------------------------------------------------
# 邮件配置
# --------------------------------------------------------------------------------------

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')

EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', '').lower()

PROVIDER_DEFAULTS = {
    'qq': {'host': 'smtp.qq.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
    '163': {'host': 'smtp.163.com', 'port': 465, 'use_tls': False, 'use_ssl': True},
    'gmail': {'host': 'smtp.gmail.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
    'outlook': {'host': 'smtp.office365.com', 'port': 587, 'use_tls': True, 'use_ssl': False},
}

provider_config = PROVIDER_DEFAULTS.get(EMAIL_PROVIDER, {})

EMAIL_HOST = os.getenv('EMAIL_HOST', provider_config.get('host', ''))
EMAIL_PORT = int(os.getenv('EMAIL_PORT') or provider_config.get('port', 587))
EMAIL_USE_TLS = (os.getenv('EMAIL_USE_TLS') or str(provider_config.get('use_tls', True))) == 'True'
EMAIL_USE_SSL = (os.getenv('EMAIL_USE_SSL') or str(provider_config.get('use_ssl', False))) == 'True'

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@ftc.local')

# --------------------------------------------------------------------------------------
# CORS (跨域资源共享) 设置
# --------------------------------------------------------------------------------------
# 开发环境
CORS_ALLOW_ALL_ORIGINS = True

# 生产环境
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]
