# Generated by Django 5.2.8 on 2025-11-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
