# Generated by Django 5.2.8 on 2025-11-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='头像链接，前端可使用对象存储上传后回填'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介 / 个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='国家/地区，便于排行榜展示', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='邮箱是否已通过验证码验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_leader',
            field=models.BooleanField(default=False, help_text='是否担任当前队伍队长（Team 模块完善后会迁移为外键判断）'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='昵称，默认等于用户名，可由选手自行修改', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='所属团队 / 学校 / 公司', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='team_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='所属队伍占位字段，后续 contests/teams 模块会替换为外键', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='个人主页或其他社交链接'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scene', models.CharField(choices=[('register', '注册'), ('reset_password', '找回密码'), ('bind_email', '绑定邮箱')], max_length=32)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'scene', 'is_used'], name='accounts_em_email_24d9bc_idx'), models.Index(fields=['scene', 'created_at'], name='accounts_em_scene_99be2c_idx')],
            },
        ),
    ]
