# Generated by Django 5.2.8 on 2025-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_avatar_user_bio_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ 邮箱'), ('163', '163 邮箱'), ('gmail', 'Gmail'), ('outlook', 'Outlook / Office365'), ('custom', '自定义 SMTP')], default='qq', max_length=20)),
                ('name', models.CharField(help_text='后台展示用名称，便于区分', max_length=50)),
                ('host', models.CharField(blank=True, max_length=120)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.EmailField(help_text='邮箱账号', max_length=254)),
                ('password', models.CharField(help_text='授权码或应用专用密码', max_length=255)),
                ('from_name', models.CharField(blank=True, help_text='展示名，如 FindTheCat 赛事组委会', max_length=100)),
                ('from_email', models.EmailField(blank=True, help_text='用于 From 的邮箱地址，默认等于 username', max_length=254)),
                ('priority', models.PositiveIntegerField(default=100, help_text='数字越小优先级越高')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='设为 True 后其余账号将自动取消默认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '发信账号',
                'verbose_name_plural': '发信账号',
                'ordering': ['priority', '-updated_at'],
            },
        ),
    ]
