# Generated by Django 5.2.8 on 2025-11-20 16:01

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_playeruser_staffuser_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.FTCUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], db_index=True, default='user', max_length=10, verbose_name='账号类型'),
        ),
    ]
