# Generated by Django 5.2.8 on 2025-11-20 16:29

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    def ensure(name: str, app_labels=None):
        group, created = Group.objects.get_or_create(name=name)
        if created and app_labels:
            perms = Permission.objects.filter(content_type__app_label__in=app_labels)
            group.permissions.set(perms)
        return group

    ensure("Users::Default")
    ensure("Admins::Default", ["contests", "challenges"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_user_account_type'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, migrations.RunPython.noop),
    ]
