# Generated by Django 5.2.8 on 2025-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_is_team_leader_remove_user_team_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否已使用'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='scene',
            field=models.CharField(choices=[('register', '注册'), ('reset_password', '找回密码'), ('bind_email', '绑定邮箱')], max_length=32, verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证时间'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='from_email',
            field=models.EmailField(blank=True, help_text='用于 From 的邮箱地址，默认等于 username', max_length=254, verbose_name='发信邮箱'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='from_name',
            field=models.CharField(blank=True, help_text='展示名', max_length=100, verbose_name='发信名称'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='host',
            field=models.CharField(blank=True, max_length=120, verbose_name='SMTP 主机'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='设为 True 后其余账号将自动取消默认', verbose_name='默认账号'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='name',
            field=models.CharField(help_text='后台展示用名称', max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='password',
            field=models.CharField(help_text='授权码或应用专用密码', max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='port',
            field=models.PositiveIntegerField(default=587, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='数字越小优先级越高', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='provider',
            field=models.CharField(choices=[('qq', 'QQ 邮箱'), ('163', '163 邮箱'), ('gmail', 'Gmail'), ('outlook', 'Outlook 邮箱'), ('custom', '自定义 SMTP')], default='qq', max_length=20, verbose_name='服务商'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='启用 SSL'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='启用 TLS'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='username',
            field=models.EmailField(help_text='邮箱账号', max_length=254, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介（个性签名）', verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='所属团队 / 学校 / 公司 / 组织', max_length=120, verbose_name='所属单位'),
        ),
    ]
