# Generated by Django 5.2.8 on 2025-11-27 13:05
"""
删除 MailAccount 模型（已迁移至 system 模块）

注意：
- 本迁移依赖 system.0009_copy_mailaccount_data 数据迁移
- 确保数据已复制到 configs_mailaccount 后再删除旧表
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_mailaccount_host'),
        ('configs', '0009_copy_mailaccount_data'),  # 确保数据已复制
    ]

    operations = [
        migrations.DeleteModel(
            name='MailAccount',
        ),
    ]
