# Generated by Django 5.2.8 on 2025-11-28 14:10

from django.db import migrations


def assign_account_ids(apps, schema_editor):
    """
    为现有用户分配 account_id

    分配策略：
    - 按用户创建时间排序
    - 超级管理员：1-10
    - 普通管理员：11-1000
    - 普通用户：1001+
    """
    User = apps.get_model('accounts', 'User')

    # 1. 为超级管理员分配 account_id (1-10)
    superusers = User.objects.filter(is_superuser=True).order_by('date_joined')
    for idx, user in enumerate(superusers, start=1):
        if idx > 10:
            raise ValueError(f"超级管理员数量超过上限（10个），当前有 {superusers.count()} 个超级管理员。请降级部分超级管理员后重新迁移。")
        user.account_id = idx
        user.save(update_fields=['account_id'])

    print(f"已为 {superusers.count()} 个超级管理员分配 account_id (1-{superusers.count()})")

    # 2. 为普通管理员分配 account_id (11-1000)
    staff_users = User.objects.filter(is_staff=True, is_superuser=False).order_by('date_joined')
    for idx, user in enumerate(staff_users, start=11):
        if idx > 1000:
            raise ValueError(f"管理员数量超过上限（990个），当前有 {staff_users.count()} 个管理员。请降级部分管理员后重新迁移。")
        user.account_id = idx
        user.save(update_fields=['account_id'])

    print(f"已为 {staff_users.count()} 个管理员分配 account_id (11-{10 + staff_users.count()})")

    # 3. 为普通用户分配 account_id (1001+)
    regular_users = User.objects.filter(is_staff=False, is_superuser=False).order_by('date_joined')
    for idx, user in enumerate(regular_users, start=1001):
        user.account_id = idx
        user.save(update_fields=['account_id'])

    print(f"已为 {regular_users.count()} 个普通用户分配 account_id (1001-{1000 + regular_users.count()})")

    total = superusers.count() + staff_users.count() + regular_users.count()
    print(f"总计为 {total} 个用户分配了 account_id")


def reverse_assign_account_ids(apps, schema_editor):
    """
    回滚操作：将所有 account_id 设为 None
    """
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(account_id=None)
    print("已清除所有用户的 account_id")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_account_id'),
    ]

    operations = [
        migrations.RunPython(assign_account_ids, reverse_code=reverse_assign_account_ids),
    ]
