# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_assign_account_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='账户ID：1-10超管，11-1000管理员，1001+普通用户', null=True, unique=True, verbose_name='ID'),
        ),
    ]
