# Generated by Django 5.2.8 on 2025-11-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_dynamic_prefix_and_more'),
        ('contests', '0004_contestscoreboard_alter_teammember_options_and_more'),
        ('submissions', '0002_submission_blood_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', 'created_at'], name='submissions_contest_fb4c14_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'user'], name='submissions_challen_2d2d82_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'team'], name='submissions_challen_b34bab_idx'),
        ),
    ]
