# Generated by Django 5.2.8 on 2025-11-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineinstance',
            name='dynamic_flag',
        ),
    ]
