# Generated by Django 5.2.8 on 2025-11-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengecategory_contest'),
        ('machines', '0003_machineinstance_machines_ma_contest_3b3e08_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeMachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='完整镜像名称，例如 registry.example.com/ftc/web:latest', max_length=255, verbose_name='容器镜像')),
                ('compose_template', models.TextField(blank=True, help_text='可选：如需多容器可粘贴 docker-compose YAML，暂未自动执行，仅用于记录', verbose_name='Compose 模板')),
                ('container_port', models.PositiveIntegerField(default=80, help_text='镜像内部服务监听端口，用于主机端口映射', verbose_name='容器服务端口')),
                ('max_instances_per_user', models.PositiveIntegerField(default=1, help_text='限制单个用户可同时运行的实例数量', verbose_name='单用户最大实例数')),
                ('max_runtime_minutes', models.PositiveIntegerField(default=30, help_text='单个实例允许的最长运行时间，超过后将自动清理', verbose_name='实例最长运行分钟数')),
                ('environment', models.JSONField(blank=True, default=dict, help_text='以 JSON 格式记录启动所需的环境变量键值对', verbose_name='环境变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('challenge', models.OneToOneField(help_text='关联的题目，每题仅允许配置一份靶机模板', on_delete=django.db.models.deletion.CASCADE, related_name='machine_config', to='challenges.challenge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目靶机配置',
                'verbose_name_plural': '题目靶机配置',
            },
        ),
    ]
