# Generated by Django 5.2.8 on 2025-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_challengemachineconfig_compose_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemachineconfig',
            name='clean_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Celery 清理任务扫描超时实例的频率', verbose_name='清理扫描间隔（秒）'),
        ),
        migrations.AddField(
            model_name='challengemachineconfig',
            name='port_cache_ttl',
            field=models.PositiveIntegerField(default=300, help_text='端口占用在 Redis 中的缓存时间，防止并发重复分配', verbose_name='端口占用缓存 TTL（秒）'),
        ),
    ]
