# Generated by Django 5.2.8 on 2025-12-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_challengemachineconfig_clean_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemachineconfig',
            name='port_cache_ttl',
            field=models.PositiveIntegerField(default=300, help_text='端口占用在 Redis 中的缓存时间', verbose_name='端口占用缓存 TTL（秒）'),
        ),
    ]
