# Generated by Django 5.2.8 on 2025-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_challengemachineconfig_extend_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemachineconfig',
            name='extend_max_times',
            field=models.IntegerField(default=-1, help_text='每一实例允许用户延时的次数，-1 表示不限制，0 表示禁止延时。', verbose_name='最大延时次数'),
        ),
        migrations.AlterField(
            model_name='challengemachineconfig',
            name='extend_minutes_default',
            field=models.PositiveIntegerField(default=30, help_text='用户点击延时追加的时间（分钟）', verbose_name='单次延时分钟数'),
        ),
        migrations.AlterField(
            model_name='challengemachineconfig',
            name='extend_threshold_minutes',
            field=models.IntegerField(default=15, help_text='仅当实例剩余时间小于等于该值时允许延时，0 或负数表示随时都可以延时', verbose_name='允许延时阈值（分钟）'),
        ),
    ]
